name: Android Build

on: push

jobs:
  build:
    name: android build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Access API_KEY
        env:
          API_KEY: "40b550b0d1a1336d1b32b6a6e7887c7e"
        run: echo API_KEY=\"$API_KEY\" > ./local.properties

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble